### ISSUE TITLE
v4.05 occasionally crashing

### ISSUE THREAD

**Issue by mikk9** [rigaya/QSVEnc#33] opened 2020-07-29 16:29 UTC
The new 4.05 is crashing sometimes. I've tried a simple CBR HEVC encode. 

C:\Staxrip\StaxRip-x64-1.7.0.0-stable\Apps\QSVEnc\QSVEncC64.exe --codec hevc --ref 3 --gop-len 256 --mbbrc --fallback-rc --cbr 2500 -i D:\Quicksync\7_Intel_Demo_Clip2.mp4 -o "D:\Quicksync\7_Intel_Demo_Clip2_temp\CBR 2500 3_3_256 mbbrc_out.hevc"

--------------------------------------------------------------------------------
D:\Quicksync\7_Intel_Demo_Clip2_temp\CBR 2500 3_3_256 mbbrc_out.hevc
--------------------------------------------------------------------------------
bitstream: failed to set parameters for hevc_metadata: Result too large.
failed to initialize file reader(s).
QSVEncC.exe finished with error!
[hevc_metadata @ 000001a36b4a2cc0] Value 109.000000 for parameter 'chroma_sample_loc_type' out of range [-1 - 6]
[hevc_metadata @ 000001a36b4a2cc0] Error setting option chroma_sample_loc_type to value 109.

Start:    18:26:01
End:      18:26:02
Duration: 00:00:00

**Comment by rigaya** [comment] 2020-08-01 23:43
Thank you, it was caused by lack of initialization in QSVEnc 4.05. It shall be fixed in [QSVEnc 4.06](https://github.com/rigaya/QSVEnc/releases/tag/4.06).

**Comment by rigaya** [comment] 2020-09-30 13:51
I'll close this issue as the problem should have been fixed.

**Closed by rigaya** 2020-09-30 13:51 UTC
