### ISSUE TITLE
Not supports QSV(hw) decoding av1

### ISSUE THREAD

**Issue by ZSC2017IM** [rigaya/QSVEnc#122] opened 2023-03-16 08:09 UTC
My dg1 can decoding av1 with ffmpeg by using "av1_qsv". However, "QSVEncC64 --avhw" report error:

MFXDEC: Failed to DecodeHeader: unknown error..
InitMfxDecParams: Failed set param for hw decoder. : unknown error.
QSVEncC.exe finished with error!

**Comment by rigaya** [comment] 2023-03-17 03:34
I've tested some AV1 files, but does not have problem on 12900K iGPU or Arc A380. If it is DG1 specific, I might not be able to fix (as I don't have DG1 GPUs), in that case the error might be avoided by using --avsw (sw decoder).

Are there any sample files out which have this issue?

**Comment by ZSC2017IM** [comment] 2023-03-17 03:55
Thank you for your reply!
On my computer, the following methods are mainly used to generate av1 videos. Currently, I do not have av1 videos from other sources. My CPU is 8700K.
OBS 29.0.2 video recorded with svt-av1 encoding.
Transcoded av1 in shanaencoder 5.3.

Video by OBS:
[2023-03-17_11-50-13.zip](https://github.com/rigaya/QSVEnc/files/10997680/2023-03-17_11-50-13.zip)

QSVEncC64 --avhw -i "2023-03-17_11-50-13.mkv" --device 1 --codec hevc -o "1.mp4"

**Comment by rigaya** [comment] 2023-03-17 13:57
Thank you for the sample file, I was able to reproduce the issue.

It seems to be a problem with AV1 in mkv format, I'll have it fixed in the next release.

**Comment by ZSC2017IM** [comment] 2023-03-17 14:55
Thanks for the fix! I just tested other MP4 encoded AV1 videos transcoded with shanaencoder with no problem, as you said it may be a problem with MKV format

**Comment by rigaya** [comment] 2023-05-10 09:11
I'll close this issue as the issue should have been solved.

**Closed by rigaya** 2023-05-10 09:11 UTC
