### ISSUE TITLE
Decoding issue with AVI files

### ISSUE THREAD

**Issue by vitduck** [rigaya/QSVEnc#211] opened 2024-08-10 05:48 UTC
Hi, 

QSVEnc failed to decode AVI file when coupling with FastFlix. 
I think there is a key component missing, perhaps a codec that I am not aware of. 

- HW: 
    - CPU: 13900k 
    - GPU: Intel A770 with latest driver (5768) 
- OS: 
    - W10 22H2 (19045.4412) 
- SW: 
    - FastFlix `v5.8.0`
   - QSVEnc `v7.68` 
   - The x264vfw codec was installed in advance following previous issue: https://github.com/rigaya/NVEnc/issues/162
   - x264 codec: https://sourceforge.net/projects/x264vfw/
- Steps to reproduce: 
   - Sample avi file: https://file-examples.com/wp-content/storage/2018/04/file_example_AVI_1280_1_5MG.avi 
   - FastFlix generated command with newline inserted for better reading: 
   ```
   "D:\Softwares\QSVEncC_7.68_x64\QSVEncC64.exe" 
        -i "C:\Users\vitduck\Desktop\sample_1280x720_surfing_with_audio.avi" 
        --video-metadata clear --metadata clear 
        --chapter-copy 
        -c hevc --cqp 25 --quality best --level auto --output-depth 8 --avsync cfr  
        --audio-stream 1?:stereo --audio-codec 1?aac --audio-bitrate 1?128k  
        --audio-metadata 1?clear --audio-disposition 1?unset   
        -m default_mode:infer_no_subs 
        -o "C:\Users\vitduck\Desktop\sample_1280x720_surfing_with_audio-fastflix-bc2e.mp4"
   ```
   - Error message: 
   ```
   avi: failed to decode avi file.

   failed to initialize file reader(s).

   QSVEncC.exe finished with error!
   ```

Regards.

**Comment by rigaya** [comment] 2024-08-10 12:14
Please try adding ```--avsw``` to switch avi reader to avsw reader.

avsw reader (using libavformat/libavcodec) will be able to handle the file fine.

Also, audio related option is not supported with avi reader. Therefore it will be better to switch to avsw to make use of audio options.

**Comment by vitduck** [comment] 2024-08-11 03:56
Thanks for the explanation. 

Adding `--avsw` has resolved the issue. 
Based on the options list my understanding is that
-  `.avi` and `.wmv` should be decoded through CPU. 
- The rest can be decoded through GPU with `--avhw` 

Please close the issue as you see fit and again thanks for your time.

**Comment by rigaya** [comment] 2024-08-11 10:30
Thank you for confirming.

I’ll close the issue as the problem is now gone.

**Closed by rigaya** 2024-08-11 10:30 UTC
